# Generated by Django 2.1.5 on 2019-03-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_funds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
