# Generated by Django 2.1.5 on 2019-03-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0003_auto_20190318_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_funds',
        ),
        migrations.AlterField(
            model_name='donation',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crowdfunder.Reward'),
        ),
    ]
