# Generated by Django 2.1.7 on 2019-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0004_auto_20190318_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='max_donations',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
